name: build
on: [push]

jobs:
  # Any checks that run pre-build
  build:
    runs-on: ubuntu-latest
    container:
      image: blang/latex:ubuntu@sha256:efd846045144c647057cceb9887a311d171abe9ed1699e92bd1ea240bbc18003
    steps:
    - uses: actions/checkout@master
    - name: Get Commit or Tag
      id: vars
      run: |
        tag="${GITHUB_SHA:0:8}"
        if [ "${GITHUB_EVENT_NAME}" == "release" ]; then
          ref="${GITHUB_REF}"
          tag=$(echo $GITHUB_REF | sed 's/refs\/tags\///g')
        fi
        echo "::set-output name=tag::$tag"
    - name: Install Task
      uses: arduino/setup-task@v1
    - name: Build pdf
      run: |
        apt update
        apt install git
        task build
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
    - name: Provide pdf
      uses: actions/upload-artifact@v2
      with:
        name: resume.pdf
        path: ./build/resume.pdf
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: resume.pdf